# Generated by Django 5.2.7 on 2025-10-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('car_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('make', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('cars_status', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied')], default='denied', max_length=10)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateplateapp.employee')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry', models.DateTimeField()),
                ('cars_status', models.CharField(max_length=10)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateplateapp.vehicle')),
            ],
            options={
                'db_table': 'accesslog',
            },
        ),
    ]
